### ISSUE TITLE
DFD Comments Feb 15

### ISSUE THREAD

**Issue by germonprez** [adamharris30/MiaDE#13]
A few comments

1) You need to include a way for the manager to actually retrieve a policy. Right now, there is no policy going back to the Manager

2) Are the two different Policy Info dataflows the same? The Find Policy vs. Set/Edit Policy section is not fully clear to me. 

MG

**Comment by adamharris30** [comment]
![screenshot - 2_16_2017 10_39_11 am](https://cloud.githubusercontent.com/assets/25037550/23030747/4a464028-f434-11e6-9d62-3605c4ac892f.png)
