### ISSUE TITLE
DFD Comments Feb 16

### ISSUE THREAD

**Issue by germonprez** [adamharris30/MiaDE#14]
1) You need to clean up the policy area a bit. Right now, there are two areas that are a bit inconsistent: 

<img width="152" alt="screen shot 2017-02-16 at 9 24 22 am" src="https://cloud.githubusercontent.com/assets/656208/23032622/e402fc34-f429-11e6-94f0-99323839cd2b.png">

<img width="79" alt="screen shot 2017-02-16 at 9 24 43 am" src="https://cloud.githubusercontent.com/assets/656208/23032623/e60d443a-f429-11e6-8902-1905ff3bfef2.png">

Policy info updates should originate from the Manager. 
Policy info is a bit vague here. You likely need more detail. 

MG

**Comment by adamharris30** [comment]
![screenshot - 2_16_2017 12_05_28 pm](https://cloud.githubusercontent.com/assets/25037550/23034107/4461b51e-f440-11e6-8658-b39c1b4090b9.png)
